# Generated by Django 4.0.4 on 2022-05-08 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_orderitem_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='user',
        ),
        migrations.AddField(
            model_name='product',
            name='deposit',
            field=models.FloatField(default=False),
        ),
    ]
